function buildPlanSchema(runnerKinds) {
  const supported = Array.isArray(runnerKinds) && runnerKinds.length
    ? runnerKinds.filter(Boolean).map((k) => String(k))
    : ['codex-cli', 'gemini-cli', 'claude-cli', 'cursor-cli', 'desktop-agent', 'auto'];

  const runKinds = supported.filter((k) => k !== 'auto');
  const setRunnerKinds = supported.includes('auto') ? supported : [...supported, 'auto'];

  const runKindsText = runKinds.map((k) => `"${k}"`).join(' | ');
  const setRunnerKindsText = setRunnerKinds.map((k) => `"${k}"`).join(' | ');

  return `{
  "version": 1,
  "action": "run" | "reply" | "set_project" | "set_runner" | "set_orchestrator" | "set_task_policy" | "memory_append" | "memory_set" | "memory_clear" | "memory_show" | "project_add" | "project_mkdir" | "project_clone" | "project_scan" | "longrun_initiate" | "longrun_gather" | "longrun_confirm" | "longrun_execute",

  // when action = "reply"
  "reply_text": string,

  // when action = "run"
  "runner_kind": ${runKindsText},
  "prompt": string,

  // when action = "set_project"
  "project_id": string,
  "create_new_task"?: boolean,

  // when action = "set_runner"
  "runner_kind": ${setRunnerKindsText},
  "scope"?: "task" | "user" | "global",

  // when action = "set_orchestrator"
  "provider": "gemini-cli" | "openrouter" | "auto",
  "scope"?: "user" | "global",

  // when action = "set_task_policy"
  "task_id_length"?: number,
  "project_task_history_limit"?: number,

  // when action = "project_add"
  "id": string,
  "cwd": string,
  "type"?: string,
  "name"?: string,

  // when action = "project_mkdir"
  "id": string,
  "dir": string,
  "type"?: string,
  "name"?: string,

  // when action = "project_clone"
  "id": string,
  "git_url": string,
  "dir"?: string,
  "depth"?: number,
  "type"?: string,
  "name"?: string,

  // when action = "memory_append" | "memory_set"
  "memory_text": string,
  "memory_scope"?: "user" | "project", // default: "user"

  // when action = "longrun_initiate"
  "feature_uuid": string,  // UUID v4 generated by the planner — will become the folder name
  "reply_text": string,    // first set of questions for the user

  // when action = "longrun_gather"
  "spec_json": string,     // JSON-stringified partial spec with all known data so far
  "reply_text": string,    // next questions or prompts for the user

  // when action = "longrun_confirm"
  "spec_json": string,     // JSON-stringified COMPLETE spec (all levels fully defined)
  "reply_text": string,    // formatted human-readable summary for user review

  // when action = "longrun_execute"
  // (no extra fields required — session is resolved from DB in inbound-core)

  // optional
  "title"?: string
}`;
}

function formatContext(messages) {
  if (!Array.isArray(messages) || messages.length === 0) return '(sem contexto anterior)';

  const lines = [];
  for (const m of messages) {
    const role = m.role || 'user';
    const content = String(m.content || '').trim();
    if (!content) continue;
    lines.push(`[${role}] ${content}`);
  }

  return lines.length > 0 ? lines.join('\n') : '(sem contexto anterior)';
}

function formatProjects(projects) {
  if (!Array.isArray(projects) || projects.length === 0) return '(nenhum projeto carregado)';
  const max = 25;
  const lines = [];
  for (const p of projects.slice(0, max)) {
    const id = p?.id || '';
    const name = p?.name || '';
    if (!id) continue;
    lines.push(`- ${id}${name && name !== id ? ` (${name})` : ''}`);
  }
  const extra = projects.length > max ? `\n(+${projects.length - max} outros)` : '';
  return lines.join('\n') + extra;
}

function formatGlobalChatHistory(entries) {
  if (!Array.isArray(entries) || entries.length === 0) return '(sem historico global)';

  const rows = [];
  const ordered = entries.slice().reverse();
  for (const item of ordered) {
    const role = String(item?.role || '').trim().toLowerCase() || 'assistant';
    const projectId = String(item?.project_id || '').trim();
    const content = String(item?.content || '').trim();
    if (!content) continue;
    const summary = String(item?.action_summary || '').trim();
    const summarySuffix = summary ? ` | action: ${summary.slice(0, 220)}` : '';
    rows.push(`[${role}${projectId ? ` @${projectId}` : ''}] ${content.slice(0, 420)}${summarySuffix}`);
  }

  return rows.length > 0 ? rows.join('\n') : '(sem historico global)';
}

function formatRunnerCatalog(runnerCatalog, fallbackRunnerKinds) {
  const kinds = Array.isArray(fallbackRunnerKinds)
    ? fallbackRunnerKinds.filter(Boolean).map((k) => String(k))
    : [];

  const list = Array.isArray(runnerCatalog) ? runnerCatalog : [];
  if (list.length === 0) {
    return kinds.length ? kinds.map((k) => `- ${k}`).join('\n') : '(catalogo indisponivel)';
  }

  const lines = [];
  for (const item of list.slice(0, 20)) {
    const kind = String(item?.kind || '').trim();
    if (!kind) continue;

    const planner = item?.planner && typeof item.planner === 'object' ? item.planner : null;
    const purpose = planner?.purpose ? String(planner.purpose).trim() : '';
    lines.push(`- ${kind}${purpose ? `: ${purpose}` : ''}`);

    const whenToUse = Array.isArray(planner?.whenToUse) ? planner.whenToUse : [];
    if (whenToUse.length > 0) {
      lines.push(`  quando_usar: ${whenToUse.join(' | ')}`);
    }

    const promptRules = Array.isArray(planner?.promptRules) ? planner.promptRules : [];
    if (promptRules.length > 0) {
      lines.push(`  prompt_rules: ${promptRules.join(' | ')}`);
    }

    const promptExamples = Array.isArray(planner?.promptExamples) ? planner.promptExamples : [];
    if (promptExamples.length > 0) {
      lines.push(`  prompt_examples: ${promptExamples.join(' | ')}`);
    }
  }

  return lines.length > 0 ? lines.join('\n') : '(catalogo indisponivel)';
}

export function buildPlannerMessages({
  userMessage,
  contextMessages,
  globalChatHistory,
  taskId,
  projectId,
  forcedRunnerKind,
  defaultRunnerKind,
  projects,
  sharedMemory,
  runnerKinds,
  runnerCatalog,
  longrunSession = null,
}) {
  const supportedRunnerKinds = Array.isArray(runnerKinds) && runnerKinds.length
    ? runnerKinds
    : ['codex-cli', 'gemini-cli', 'claude-cli', 'cursor-cli', 'desktop-agent', 'auto'];
  const runRunnerKinds = supportedRunnerKinds.filter((k) => k !== 'auto').join(', ');
  const runnerCatalogText = formatRunnerCatalog(runnerCatalog, supportedRunnerKinds);
  const forcedRunner = String(forcedRunnerKind || '').trim().toLowerCase();
  const hasForcedRunner = Boolean(forcedRunner && forcedRunner !== 'auto');

  const system = [
    'Voce e o orquestrador principal do "morpheus".',
    'Sua saida DEVE ser APENAS um unico JSON valido (sem markdown, sem texto extra).',
    'Nao execute ferramentas, nao rode comandos, nao leia arquivos. Apenas planeje.',
    '',
    'Quando a mensagem do usuario for apenas um cumprimento (ex.: "oi", "ola", "bom dia") ou estiver vaga, use action="reply" e responda curto com instrucoes (/help, /status, /projects, /runner, /orchestrator).',
    'Quando for um pedido de trabalho, use action="run" e gere um prompt claro e completo (em PT-BR) para o runner executar com o workspace do projeto como contexto.',
    '',
    'Escolha do runner_kind (muito importante):',
    '- Use runner_kind="desktop-agent" quando o pedido exigir acoes na interface do computador: abrir apps, navegar em sites, clicar, preencher campos, ler conteudo visual, tirar prints/screenshot, verificar algo "na tela".',
    '- Use runner_kind="desktop-agent" tambem quando o usuario pedir explicitamente imagens/prints como evidencia.',
    '- Caso contrario, prefira o runner default (codex/claude/cursor/gemini) para tarefas de codigo e shell.',
    '- Se existir um runner externo especializado para a tarefa no catalogo abaixo, prefira esse runner especializado.',
    '- Quando um runner tiver `prompt_rules`, voce DEVE gerar `plan.prompt` estritamente nesse formato.',
    ...(hasForcedRunner
      ? [
          `- Runner travado para esta task: "${forcedRunner}".`,
          `- Quando action="run", use obrigatoriamente runner_kind="${forcedRunner}" e siga as regras desse runner no catalogo.`,
        ]
      : []),
    'Importante: o runner pode usar caminhos fora do projeto (ex.: criar/alterar coisas em DEVELOPMENT_ROOT) quando isso for necessario para cumprir o pedido. Seja explicito com paths absolutos e passos de validacao.',
    '',
    'Catalogo de runners (MCP-like):',
    runnerCatalogText,
    '',
    'Quando o usuario pedir algo de configuracao em linguagem natural (sem comandos /...):',
    '- Trocar de projeto: use action="set_project" (nao use action="run").',
    '- Trocar runner: use action="set_runner" (scope "task" quando for so para esta task; "user" para preferencia do usuario; "global" apenas se o usuario for admin).',
    '- Trocar orchestrator/planner: use action="set_orchestrator" (scope "user" ou "global").',
    '- Alterar politica de tasks (tamanho do task_id e limite de historico por projeto): use action="set_task_policy".',
    '- Memoria: use action="memory_append" para adicionar uma anotacao; use action="memory_set" para substituir; use action="memory_clear" para limpar; use action="memory_show" para mostrar.',
    '- Para memoria global do usuario, use memory_scope="user" (ou omita memory_scope).',
    '- Para memoria do projeto atual, use memory_scope="project".',
    '- Criar/registrar projetos (admin): use action="project_mkdir" / "project_clone" / "project_add" / "project_scan".',
    '- Para project_mkdir/project_clone: prefira `dir` relativo ao DEVELOPMENT_ROOT, mas path absoluto tambem e permitido se o usuario pediu.',
    'Regras:',
    '- Se action="reply": reply_text e obrigatorio.',
    `- Se action="run": prompt e runner_kind sao obrigatorios e runner_kind deve ser um dos runners suportados: ${runRunnerKinds}.`,
    '',
    'Schema do JSON:',
    buildPlanSchema(supportedRunnerKinds),
    '',
    `Runner preferido (nao obrigatorio): "${defaultRunnerKind}". Se action="run", escolha explicitamente um runner_kind (nao omita).`,
    '',
    'LongRun - execucao automatica e recursiva de features complexas:',
    'Se o usuario mencionar "longrun", "long run", "ralph loop", "execucao automatica", "executar feature completa" ou similar:',
    '',
    'FASE DE COLETA — primeira mensagem de intencao (sem sessao ativa):',
    '- Use action="longrun_initiate" com:',
    '    feature_uuid: um UUID v4 novo gerado agora pelo planner (sera o nome da pasta)',
    '    reply_text: primeiras perguntas obrigatorias ao usuario',
    '- Perguntas obrigatorias: titulo da feature, descricao detalhada, stack/linguagem, estrutura do repo (monorepo? apps?), contexto de negocio, criterios de validacao por funcionalidade, restricoes tecnicas.',
    '',
    'FASE DE COLETA — turnos subsequentes (sessao ativa em status=gathering):',
    '- Use action="longrun_gather" com:',
    '    spec_json: partial spec ACUMULATIVO serializado como string JSON — inclua TUDO o que foi coletado ate agora, mesmo que incompleto.',
    '    reply_text: proximas perguntas ao usuario',
    '- O spec_json e escrito em disco a cada turno como fonte de verdade incremental.',
    '  Mesmo apos compactacao de contexto, o spec parcial e reinjetado no proximo turno.',
    '- Gere automaticamente (sem pedir ao usuario): organizacao em Waves (blocos operacionais,',
    '  ordem de execucao, paralelismo possivel), Epic Groups por wave, Epics com specs tecnicas',
    '  (MINIMO 3 tasks por epic, mais tasks = melhor granularidade), Tasks granulares (cada uma = 1 commit).',
    '- Quando TUDO estiver coletado e estruturado: use action="longrun_confirm".',
    '',
    'FASE DE CONFIRMACAO (sessao ativa em status=confirming):',
    '- Use action="longrun_confirm" com:',
    '    spec_json: spec COMPLETO serializado como string JSON (todos os niveis preenchidos)',
    '    reply_text: resumo formatado e legivel com hierarquia completa para revisao do usuario',
    '- Se usuario confirmar ("confirmo", "ok", "pode executar", "sim", "start"): use action="longrun_execute"',
    '- Se pedir modificacoes: use action="longrun_gather" com spec_json atualizado',
    '- NUNCA inicie execucao sem confirmacao explicita do usuario',
    '',
    'Formato do spec_json (estrutura completa):',
    '{ "feature": { "uuid": "...", "title": "...", "description": "..." },',
    '  "waves": [{ "uuid": "...", "title": "...", "order": 1, "parallel": false,',
    '    "epic_groups": [{ "uuid": "...", "title": "...", "description": "...",',
    '      "epics": [{ "uuid": "...", "title": "...", "description": "...",',
    '        "validation_instructions": "Run: npm test. Criterios: ...",',
    '        "tasks": [{ "uuid": "...", "title": "...", "description": "..." }]',
    '      }]',
    '    }]',
    '  }]',
    '}',
    '',
    'Regras LongRun:',
    '- UUIDs v4 unicos em todos os niveis (feature, wave, epic_group, epic, task).',
    '- Runner priority: claude-cli > codex-cli > gemini-cli > cursor-cli.',
    '- Se usuario forcou um runner especifico: pergunte confirmacao antes de aceitar.',
    '- Tasks sao granulares: cada uma deve gerar 1 commit com mudanca coesa e testavel.',
    '- Epics devem ter instrucoes de validacao claras (quais testes rodar, o que verificar).',
    '- Waves podem ter parallel=true quando o desenvolvimento nao causar conflitos entre si.',
  ].join('\n');

  const longrunSessionLines = [];
  if (longrunSession) {
    longrunSessionLines.push('');
    longrunSessionLines.push(`LongRun sessao ativa (status=${longrunSession.status}): feature_uuid=${longrunSession.feature_uuid || '(pendente)'}, titulo="${longrunSession.feature_title || '(sem titulo)'}"`);
    if (longrunSession.spec_json && String(longrunSession.spec_json).trim()) {
      const specPreview = String(longrunSession.spec_json).slice(0, 3000);
      longrunSessionLines.push(`Spec parcial atual (fonte de verdade — primeiros 3000 chars):\n${specPreview}`);
    } else {
      longrunSessionLines.push('(spec ainda nao iniciado)');
    }
  }

  const user = [
    `task_id: ${taskId}`,
    `project_id: ${projectId}`,
    '',
    'Memorias atuais (compartilhada + projeto atual):',
    sharedMemory && String(sharedMemory).trim() ? String(sharedMemory).trim() : '(vazia)',
    '',
    'Historico global recente (cross-task, pode ter resumo de acoes):',
    formatGlobalChatHistory(globalChatHistory),
    '',
    'Projetos disponiveis (parcial):',
    formatProjects(projects),
    '',
    'Contexto recente (task-scoped):',
    formatContext(contextMessages),
    ...longrunSessionLines,
    '',
    'Mensagem atual do usuario:',
    userMessage,
  ].join('\n');

  return { system, user };
}
